### ISSUE TITLE
Optionally include full history in the changelog output

### ISSUE THREAD

**Issue by amynbe** [JetBrains/gradle-changelog-plugin#1]
I like to include the full changelog history in the release notes, so that people who are jumping several versions can see what they've been missing since the last time.

This is especially useful when I publish a series of releases close to each other.

This could be done in the form of a from and to version arguments?

Or maybe some developers might like to display the latest x number of versions (just an idea but that's not my case personally, I just want the full history).

Thanks for the work so far.

**Comment by hsz** [comment]
Amyn putting the whole changelog history into the Release Notes section is something that I'd like to avoid - this is not how you should use such field.
Release Notes is supposed to be a piece of information regarding the changes included in the delivered version.
Providing a full history is very void and makes such section messy and hard to read:

![image](https://user-images.githubusercontent.com/108333/83911577-ce706380-a76c-11ea-9560-6ceb7933ad73.png)

The proper way is to provide the latest changes + optionally a link to the full `CHANGELOG.md` file.

Maybe it'd be better to extend the `plugin.xml` scheme with some `<changelog-url>` element and how such URL in the plugin's details in the IDE/MarketPlace?

**Comment by amynbe** [comment]
Your screenshot looks quite good to me actually, don't think it's really unreadable? My plugin:
![image](https://user-images.githubusercontent.com/1658509/83916235-b698df80-a76c-11ea-95de-67386932cf0e.png)

Editing `<change-notes>` in `plugin.xml` makes this trivially easy, and I think `gradle-changelog-plugin` doesn't need to be so opinionated about this that it makes it impossible to do.

How about making it less obvious but still possible to the stubborn dev by changing the visibility of `Changelog.items` to public?

**Comment by hsz** [comment]
Since `v0.4.0`, there is `getAll` method available. 
Check [README](https://github.com/JetBrains/gradle-changelog-plugin#getall) for more details.
