### ISSUE TITLE
Issue with custom header

### ISSUE THREAD

**Issue by PrzemyslawSwiderski** [JetBrains/gradle-changelog-plugin#10]
Hi,
I have problem with the latest released version (`0.5.0`).
I am trying to specify header with the following config in `build.gradle.kts` file:
```
changelog {
    header = { "[${project.version}] - ${date()}" }
}
```
Unfortunately, build script can not be executed due to: `(...) build.gradle.kts:25:14: Type mismatch: inferred type is () -> String but Closure<*> was expected` error.

**Comment by hsz** [comment]
For Gradle, `header = { }` is enough, but KTS requires additional `closure` here, as described in the README:

```
import org.jetbrains.changelog.closure
import org.jetbrains.changelog.date

changelog {
    header = closure { "[${project.version}] - ${date()}" }
}
```

**Comment by PrzemyslawSwiderski** [comment]
Oh I see. Thanks.
