### ISSUE TITLE
Cannot use `headerParserRegex`

### ISSUE THREAD

**Issue by AlexPl292** [JetBrains/gradle-changelog-plugin#11]
Hi!
I'm trying to set up custom regex for parsing plugin version in the groovy config. I've used
```
changelog {
  headerParserRegex = /0\.\d{2}/
}
```
but I'm getting an error: `Cannot cast object '0\.\d{2}' with class 'java.lang.String' to class 'kotlin.text.Regex'`

**Comment by citizenmatt** [comment]
I had to create a new `Regex` instance.

https://github.com/JetBrains/resharper-unity/blob/af713f739cf7d96c11e3eee5f6893f3c4883b021/rider/build.gradle#L48

**Comment by AlexPl292** [comment]
Oh, thanks. I haven't understood that kotlin classes are accessible from `gradle.build`.

**Comment by hsz** [comment]
@AlexPl292, thanks for pointing it out! I've updated README with some examples and a better description.

**Comment by AlexPl292** [comment]
Did you something special to help IJ understand that kotlin works for gradle? Because now my `build.gradle` is red.
<img width="323" alt="Screenshot 2020-10-13 at 11 03 55" src="https://user-images.githubusercontent.com/4203721/95833157-ec198f00-0d43-11eb-83c0-a6a2b74adeed.png">
<img width="435" alt="Screenshot 2020-10-13 at 11 03 51" src="https://user-images.githubusercontent.com/4203721/95833163-ede35280-0d43-11eb-919c-d16fe76106fb.png">
