### ISSUE TITLE
wrong version number

### ISSUE THREAD

**Issue by zoulejiu** [JetBrains/gradle-changelog-plugin#112]
Hello
  I found that when the version number is set to 1.4, the plugin cannot be resolved, and the version number must be changed to 1.4.0 to work properly

**Comment by YannCebron** [comment]
where did you find instruction to use `1.4` instead of `1.4.0`?

**Comment by zoulejiu** [comment]
![image](https://user-images.githubusercontent.com/31949635/165312717-6a23da97-b776-47e5-b1e8-237f11d0f3e8.png)

**Comment by zoulejiu** [comment]
I extracted the regular expression for parsing this version number and found that only the format of x.x.x will be parsed normally
