### ISSUE TITLE
Support `*` lists in changelog.md for getChangelog task

### ISSUE THREAD

**Issue by nico-loeber** [JetBrains/gradle-changelog-plugin#117]
**Is your feature request related to a problem? Please describe.**
I have automated my release workflow including patching the changes in the plugin automatically by the changelog.md of the repository.
This failed for my last release. I didn't realized that I used `* list item` instead of `- list item`, as some of the GitHub generated automatic changelog components (new contributors and merged pull requests) already used `*` for listings.

**Describe the solution you'd like**
As both symbols can be used in Markdown to create a list, `*` should be treated equal `-` when extracting the changelog.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by citizenmatt** [comment]
You can use the `itemPrefix` configuration property to specify the prefix for list items. The default value is `-` but can be set to `*`. There are details in the help in the README

**Comment by nico-loeber** [comment]
> You can use the `itemPrefix` configuration property to specify the prefix for list items. The default value is `-` but can be set to `*`. There are details in the help in the README

Thanks for your reply!
Is it possible to allow both?

**Comment by hsz** [comment]
No, you need to specify one.
