### ISSUE TITLE
`ChangelogSectionUrlBuilder` is not configuration cache friendly if used as a lambda

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JetBrains/gradle-changelog-plugin#141]
Looks like the Gradle configuration cache is incompatible with `fun interface` as if I implement it with `object : ChangelogSectionUrlBuilder` it works perfectly (when it is provided externally as with the one applied by the plugin works perfectly).

What do you think about removing the `fun` part of that interface? Not sure if there is a missing test to check compatibility with the configuration cache providing all properties and not using the default ones.

**Comment by hsz** [comment]
I tried two approaches:

- Kotlin DSL
  ```Kotlin
  changelog {
      sectionUrlBuilder.set(ChangelogSectionUrlBuilder { repositoryUrl, currentVersion, previousVersion, isUnreleased ->
          "foo"
      })
  }
  ```

- Groovy
  ```Groovy
  changelog {
      sectionUrlBuilder = { repositoryUrl, currentVersion, previousVersion, isUnreleased ->
          "foo"
      } as ChangelogSectionUrlBuilder
  }
  ```

In the `gradle.properties` file, I explicitly enabled the Gradle configuration cache with the following:

```properties
org.gradle.unsafe.configuration-cache = true
```

With such a setup, everything works correctly when patching the changelog file.
FTR, I tested it using Gradle `7.6` and `8.0.2`.

In addition, this `changelog.sectionUrlBuilder` property now also has extra test cases to be sure it doesn't break caching:
https://github.com/JetBrains/gradle-changelog-plugin/commit/137cecf2d532fcb8c2097f419afc340297d9b37c

**Comment by JavierSegoviaCordoba** [comment]
If I see this again I will reopen it.
