### ISSUE TITLE
Sub-bullets remove root bullet

### ISSUE THREAD

**Issue by Roboroads** [JetBrains/gradle-changelog-plugin#147]
**Describe the bug**
When patching the changelog (using [JetBrains/intellij-platform-plugin-template](https://github.com/JetBrains/intellij-platform-plugin-template) next branch) the sub-bullets replace the root bullet.

**To Reproduce**
Create a changelog with sub bullets (actual example from [my repo](https://github.com/Roboroads/laravel-tinker))
```md
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
### Added
- Add way to customize vendor path.
  - Also fixed the bug from this PR where it crashed if you didn't configure anything.
- Add ANSI mode parsing (instead of regex-replace-guessing in the output window)
```

When patched, the new changelog looks like this:

```md
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [2.5.0]
### Added
- - Also fixed the bug from this PR where it crashed if you didn't configure anything.
- Add ANSI mode parsing (instead of regex-replace-guessing in the output window)
```

**Expected behavior**

```md
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [2.5.0]
### Added
- Add way to customize vendor path.
  - Also fixed the bug from this PR where it crashed if you didn't configure anything.
- Add ANSI mode parsing (instead of regex-replace-guessing in the output window)
```

**Environment:**
 - OS: Gitlab Runner (Ubuntu)
 - Gradle Changelog Plugin Version 2.0.0
 - Gradle Version 7.5.1

**Comment by 4ch1m** [comment]
I can confirm that bug.

The (valid) markdown is being rendered just fine in the preview:

<img src="https://user-images.githubusercontent.com/3408832/217033659-1288c6f7-add2-4913-a4e0-4df622978129.png" width=60% height=60%>

However, the plugin is rendering this:

<img src="https://user-images.githubusercontent.com/3408832/217033889-b4dd93a8-3d8c-4f41-ac48-d344e5ce85b5.png" width=40% height=40%>

**Comment by YannCebron** [comment]
https://github.com/YannCebron/m68kplugin/commit/52cf846b4384439723d89fc0ed198dd989b4e97e

since it affected "old" versions I caught it only by accident

**Comment by JojOatXGME** [comment]
I noticed this issue is not specific to (sub-)bullets. The plugin generally seems to skip/remove all but the last paragraph for each bullet. For example,

```
- AA
- BB

  CC

  DD
- EE
```

becomes

```
- AA
- DD
- EE
```
