### ISSUE TITLE
"Unable to resolve class org.jetbrains.changelog.date" in gradle groovy build file

### ISSUE THREAD

**Issue by ChrisCarini** [JetBrains/gradle-changelog-plugin#17]
Hello, first off, this plugin is awesome! Thank you for creating it!

I am trying to use this in one of my IJ plugins (in prep for all of them!), and getting the below error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ccarini/GitHub/intellij-notification-sample/build.gradle' line: 1

* What went wrong:
Could not compile build file '/Users/ccarini/GitHub/intellij-notification-sample/build.gradle'.
> startup failed:
  build file '/Users/ccarini/GitHub/intellij-notification-sample/build.gradle': 1: unable to resolve class org.jetbrains.changelog.date
   @ line 1, column 1.
     import org.jetbrains.changelog.date
     ^
  
  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 208ms
```

This looks very similar / identical to #14 (but, that issue was closed with no details, so it is hard to tell).

I am using:
- `id 'org.jetbrains.changelog' version '0.6.2'`
- gradle wrapper version `6.2`

I created a PR with the changes suggested by the `README.md` -> https://github.com/ChrisCarini/intellij-notification-sample/pull/1

**NOTE:** The above PR works fine as-is, because I am not using `date()` as the docs suggest, but rather `new Date().format('yyyy-MM-dd')` as a workaround. The changes needed to reproduce the above error are:
1. Uncomment line #1 of `build.gradle`
1. Uncomment line #58 of `build.gradle`
1. Comment out line #59 of `build.gradle`

Perhaps I am missing something silly here - please advise!

**Comment by hsz** [comment]
Chris, I'm happy that you like it!
In fact, the Groovy example from the README is invalid.

Changelog plugin is written in Kotlin, and such helper methods are the package-level functions:

```kotlin
package org.jetbrains.changelog

// ...

fun date(pattern: String = "yyyy-MM-dd") = SimpleDateFormat(pattern).format(Date())!!
```

To import such function properly in Groovy or Java, it's required to import the file first, as a class – then call the proper method:

```groovy
import org.jetbrains.changelog.ExtensionsKt

// ...

changelog {
    header = { "[${project.version}] - ${ExtensionsKt.date('yyyy-MM-dd')}" }
}
```

I'll update docs with the correct import.
Thanks for pointing it out!

PS. I wonder why it didn't come out earlier.
