### ISSUE TITLE
Duplicated and incorrect repository links

### ISSUE THREAD

**Issue by krasa** [JetBrains/gradle-changelog-plugin#175]
**Describe the bug**
- duplicated repository links after every `publishPlugin` https://github.com/krasa/StringManipulation/blob/test/CHANGELOG.md?plain=1
- incorrect link  https://plugins.jetbrains.com/plugin/2162-string-manipulation/versions/test/347843
![image](https://github.com/JetBrains/gradle-changelog-plugin/assets/1160875/85ff14ad-fe88-4130-a20b-31ed0b457fb8)

**To Reproduce**
- have an unreleased change `foo` https://github.com/krasa/StringManipulation/commit/2c1129a5f91874681ebad700c33425e54c6ea459
- increment plugin version and do `publishPlugin` -> result https://github.com/krasa/StringManipulation/commit/7a46157ceb32dd96d2409b0824dbf25c1b637e48 + https://plugins.jetbrains.com/plugin/2162-string-manipulation/versions/test/347843

**Expected behavior**
- not duplicating links
- proper link in the What’s New section

**Environment:**
 - OS: Win10
 - Gradle Changelog Plugin Version 2.1.0
 - Gradle Version 8.1
 

**Additional context**
- disabled `org.gradle.configuration-cache` for testing purposes
- [changelog config ](https://github.com/krasa/StringManipulation/blob/7a46157ceb32dd96d2409b0824dbf25c1b637e48/build.gradle.kts#L80-L83)  + https://github.com/krasa/StringManipulation/blob/7a46157ceb32dd96d2409b0824dbf25c1b637e48/build.gradle.kts#L123-L132

**Comment by hsz** [comment]
It seems this is a Windows-specific issue and #177 should be able to fix it.
Could you please verify it with the `2.1.1` release?
