### ISSUE TITLE
org.jetbrains.changelog.Changelog.Item.plus doesn't keep `withHeader` and other boolean flags

### ISSUE THREAD

**Issue by rybak** [JetBrains/gradle-changelog-plugin#179]
**Describe the bug**
I'm trying to _add_ additional list items to `<change-notes>` in the Gradle task `patchPluginXml` of Gradle IntelliJ Plugin. I'm trying to modify output of the Changelog Plugin. Unfortunately, function `org.jetbrains.changelog.Changelog.Item.plus` loses the value of `withHeader` and other boolean flags, which were set up in the call chain before `plus()` is invoked.

Below is a minimal example that doesn't require Gradle IntelliJ Plugin.

**To Reproduce**
This is code, slightly modified from [IntelliJ Platform Plugin Template](https://github.com/JetBrains/intellij-platform-plugin-template/blob/main/build.gradle.kts#L72-L102). Two methods `withHeader` and `withEmptySections` are used as an example – these are just the two boolean flags that I've checked, others are probably affected in the same way. 

1. Put the following code at the top level of the `build.gradle.kts`, for simplicity:
```kotlin
with(project.changelog) {
	val extraItems = mapOf(
		"Extra section" to setOf("[Extra link](https://example.org)")
	)
	println(renderItem(
		getUnreleased()
			.withHeader(false)
			.withEmptySections(true)
			.plus(Changelog.Item("", "", "", false, extraItems, "", "")),
		Changelog.OutputType.MARKDOWN
	))
}
```
2. Put the following Markdown text in `CHANGELOG.md`:
```
# Changelog

## [Unreleased]

### Added
- Example added item, "Changed" is empty

### Changed

## [0.2.0-alpha]

[Unreleased]: https://github.com/rybak/intellij-copy-commit-reference/compare/v0.2.0-alpha...HEAD
[0.2.0-alpha]: https://github.com/rybak/intellij-copy-commit-reference/compare/v0.1.0-alpha.1...v0.2.0-alpha
```
3. Run `./gradlew`

**Actual behavior**
Header `## [Unreleased]` is printed in the log, empty section is absent:
```
## [Unreleased]

### Added
- Example added item, "Changed" is empty

### Extra section
- [Extra link](https://example.org)

[Unreleased]: https://github.com/rybak/intellij-copy-commit-reference/compare/v0.2.0-alpha...HEAD
```

**Expected behavior**
Header is _not_ printed in the log, empty section is present:
```
### Added
- Example added item, "Changed" is empty

### Changed

### Extra section
- [Extra link](https://example.org)

[Unreleased]: https://github.com/rybak/intellij-copy-commit-reference/compare/v0.2.0-alpha...HEAD
```

**Environment:**
 - Gradle Changelog Plugin Version 2.1.0
 - Gradle Version 8.1.1

**Additional context**
* Workaround – call `with*` functions _after_ the `plus` function:
```kotlin
with(project.changelog) {
	val extraItems = mapOf(
		"Extra section" to setOf("[Extra link](https://example.org)")
	)
	println(renderItem(
		getUnreleased()
			.plus(Changelog.Item("", "", "", false, extraItems, "", ""))
			.withHeader(false)
			.withEmptySections(true),
		Changelog.OutputType.MARKDOWN
	))
}
```
* I'm not yet familiar with how `copy()` works in Kotlin, but this bug has something to do with the fact that [function `plus()`](https://github.com/JetBrains/gradle-changelog-plugin/blob/main/src/main/kotlin/org/jetbrains/changelog/Changelog.kt#L318-L327) is not calling [`private fun copy`](https://github.com/JetBrains/gradle-changelog-plugin/blob/main/src/main/kotlin/org/jetbrains/changelog/Changelog.kt#L289-L327). Instead, the [constructor, which sets the default values for affected flags](https://github.com/JetBrains/gradle-changelog-plugin/blob/main/src/main/kotlin/org/jetbrains/changelog/Changelog.kt#L254-L268) is invoked.

**Comment by hsz** [comment]
Thanks for reporting, @rybak!
Indeed, an incorrect `copy` was picked. Fixed with this workaround: 992281eccb5a8e726a3f339d8ef26e5910d2741e
