### ISSUE TITLE
Getting Changelog for a version fails when running through gradle wrapper

### ISSUE THREAD

**Issue by anikrajc** [JetBrains/gradle-changelog-plugin#188]
**Describe the bug**
When running the following command,
```
 ./gradlew getChangelog -q --no-header --no-summary --version=1.0.1
```
The command fails with Gradle Wrapper help menu
```
Command-line option '--version' does not take an argument.

USAGE: gradlew [option...] [task...]
```

**To Reproduce**
Using 2.1.2 version of the library on a kotlin multiplatform project. You can reproduce this with any gradle project and running the command through the terminal.

**Expected behavior**
The changelog of the given version should have been displayed

**Environment:**
 - OS: macOS
 - Gradle Changelog Plugin Version 2.1.2
 - Gradle Version 7.6.1

**Comment by hsz** [comment]
Thanks for reporting, Anik.
Turns out, `--version` option conflicts with Gradle's one. I've renamed it to `--project-version`.

The fix will be available with the next release.
