### ISSUE TITLE
Generated markdown is invalid according to markdownlint

### ISSUE THREAD

**Issue by brodock** [JetBrains/gradle-changelog-plugin#190]
**Describe the bug**
Running the `patchChangelog`, removes the empty line between the Level 2 and Level 3 Headers and any list item present there, which is considered invalid by markdownlint.

**To Reproduce**

1. Include items in the unreleased section.
2. Run `patchChangelog` task
3. Run `markdownlint` against `CHANGELOG.md`

This is an example of the violations:

```
CHANGELOG.md:15 MD022/blanks-around-headings/blanks-around-headers Headings should be surrounded by blank lines [Expected: 1; Actual: 0; Below] [Context: "### Changed"]
CHANGELOG.md:16 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "- Some content you added to the Unreleased section"]
```

**Expected behavior**
The generated Markdown should include an empty line after the Level 3 headers. This is enough to comply with both violations.

**Environment:**
 - OS: `macOS Ventura 13.5`
 - Gradle Changelog Plugin Version: `2.1.2`
 - Gradle Version: `8.2.1`

**Additional context**

**Comment by hsz** [comment]
Thanks for reporting, Gabriel!
Since the next release, headings and lists will be surrounded with blank lines.
