### ISSUE TITLE
Sample combining it with Dokka

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [JetBrains/gradle-changelog-plugin#36]
I think a common use case can be to reference the HTML Changelog in published docs with Dokka, should be great to have a sample about that.

**Comment by hsz** [comment]
@JavierSegoviaCordoba, could you please provide more details on that?

**Comment by JavierSegoviaCordoba** [comment]
I haven't a lot of knowledge about Dokka, so I don't know if this is possible at this time, but, currently, Dokka generated this menu:

![image](https://user-images.githubusercontent.com/7463564/109177247-e3bc7080-7787-11eb-9665-20189f27c660.png)

Should be great to have a section there called `Changelog` to see the Changelog generated by the plugin (so I think it is needed to generate the changelog to HTML with the task this plugin provides and add it, in some way, to the Dokka webpage).

**Comment by MarcinAman** [comment]
For the dokka part it would require some work on creating a plugin for it. This plugin would add a custom [page](https://kotlin.github.io/dokka/1.4.20/developer_guide/data_model/#page-model) to the pages tree and to the menu.

I see that you are using a mutlimodule project as a sample, please note that our multimodule approach has changed a little bit and in 1.4.30 users will be able to see all modules in the navigation. If you want to check it out for yourself you can grab one of our dev builds from space packages, just add the repository `maven("https://maven.pkg.jetbrains.space/kotlin/p/dokka/dev")` and version `1.4.20.2-dev-64`.
