### ISSUE TITLE
Support for creating groups in configuration

### ISSUE THREAD

**Issue by rohithThammaiah** [JetBrains/gradle-changelog-plugin#6]
A field in configuration which adds groups while running a patch, Something in the lines of
``` groovy
changelog {
    version = "${project.version}"
    path = "${project.projectDir}/CHANGELOG.md"
    headerFormat = "[{0}]"
    headerArguments = ["${project.version}"]
    itemPrefix = "-"
    keepUnreleasedSection = true
    unreleasedTerm = "[Unreleased]"
    groups = ["Features","Bug Fixes","Removal"]
}
```

**Comment by hsz** [comment]
Thanks for this feature request!
It's implemented and released with `v0.4.0`.
Check [README](https://github.com/JetBrains/gradle-changelog-plugin#configuration) for more details.
