### ISSUE TITLE
Wording in the description seems wrong in Readme.md

### ISSUE THREAD

**Issue by dhirupandey** [JetBrains/gradle-changelog-plugin#7]
Something about the wording of the description seems off here:

> A Gradle plugin that provides tasks and helper methods to let the working with the changelog managed in a keep a changelog style easier.

May be its me, but I thought its best to file an issue and let the experts decide

**Comment by hsz** [comment]
Thanks, @dhirupandey!
I have passed this sentence to our copyeditors - I hope that the current version is much better. 🙂

**Comment by dhirupandey** [comment]
Reads much better. Thanks @hsz !
