### ISSUE TITLE
Windows toPlainText() inserts extra newlines

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/gradle-changelog-plugin#8]
When producing plain text output on Windows, a simple list gets extra newlines inserted. I think this is because internally everything is handled as Unix style line endings (`\n`) rather than Windows style. I can recreate this in a build, but not in a test.

You can try this in the [Unity plugin (net202 branch)](https://github.com/JetBrains/resharper-unity). Firstly, run `.\build.ps1` to make sure all the right things are downloaded, then cd into `rider` and run `.\gradlew packReSharperPlugin`. In the `<root>\resharper\build\distributions\Debug\` folder is a `.nupkg` file. Unzipping this will give a `.nuspec` file, with recent changes listed with an extra separating line. Building the same target on Unix generates the plain text changelog without extra newlines.

You can see the difference in [this release](https://plugins.jetbrains.com/plugin/11629-unity-support/versions/stable/95073) vs [this hand edited release](https://plugins.jetbrains.com/plugin/11629-unity-support/versions/stable/95077)

**Comment by hsz** [comment]
Hey, Matt – is it still the case? :)

**Comment by hsz** [comment]
Closing as obsolete.
