### ISSUE TITLE
`patchChangelog` task removes user entered text anywhere in the file

### ISSUE THREAD

**Issue by bric3** [JetBrains/gradle-changelog-plugin#95]
Suppose you added some lines that are not supposed to be listed, eg an introduction or a summary in defined `changelog.md` file.

```
## [Unreleased]


## [0.2.3-eap] - 2021-12-06

This is the very first release to do this thing, proceed with caution. Etc. Etc.
Also the project is stopping support this ...

* item a
* item b

TODO
- [ ] i
- [ ] ii
- [X] iii
- [X] iv

```

And during the release workflow there is task that patches whatever the user entered for a new release.

```yml
- name: Patch Changelog # If it was changed in the Edit Release UI
  run: |
    ./gradlew patchChangelog --release-note "$(cat << 'EOM'
    ${{ github.event.release.body }}
    EOM
    )"
```

However the task actually removes lines that do not start with the defined prefix (like `*`).

```diff
## [Unreleased]
+ ### What's comming from github
+ 
+ * item 1

## [0.2.3-eap] - 2021-12-06
- 
- This is the very first release to do this thing, proceed with caution. Etc. Etc.
- Also the project is stopping support this ...

* item a
* item b

- TODO
- - [X] i
- - [X] ii
- - [ ] iii
- - [ ] iv

```

**Comment by hsz** [comment]
With #127, a `summary` property was introduced that allows for adding extra content before (only) the changelog items.
In your case, the first part will be kept – TODO will still vanish.

**Comment by bric3** [comment]
For reference there's also a another workaround for these cases by configuring `itemPrefix.set("")`.
